name: Workflow prueba

on: push

jobs:
  tarea1:
    runs-on: ubuntu-latest 
    
    permissions: 
      security-events: write
      
    steps:
    - name: Analisis
      uses: advanced-security/python-lint-code-scanning-action@v1
      with:
        linter: pylint

      
